(import [super [Eq = !=]])
(import [primitives [Option Some None String Bool]])
(defn test-int-eq [] : (Option String)
  (if (= 1 1) None (Some "expected (= 1 1) true")))
(defn test-int-neq [] : (Option String)
  (if (= 1 2) (Some "expected (= 1 2) false") None))
(defn test-int-bang-eq [] : (Option String)
  (if (!= 1 2) None (Some "expected (!= 1 2) true")))
(defn test-bool-eq [] : (Option String)
  (if (= true true) None (Some "expected (= true true) true")))
(defn test-string-eq [] : (Option String)
  (if (= "a" "a") None (Some "expected string eq true")))
(defn test-string-bang-eq [] : (Option String)
  (if (!= "a" "b") None (Some "expected string neq true")))