[workspace]
members = [
    ".",
    "crates/cranelisp-types",
    "crates/cranelisp-frontend",
    "crates/cranelisp-typecheck",
    "crates/cranelisp-backend",
    "crates/cranelisp-runtime",
    "crates/cranelisp-platform",
    "crates/cranelisp-exe-bundle",
    "platforms/stdio",
    "platforms/test-capture",
]
resolver = "2"

[package]
name = "cranelisp"
version = "0.1.0"
edition = "2024"

[dependencies]
cranelisp-types = { path = "crates/cranelisp-types" }
cranelisp-frontend = { path = "crates/cranelisp-frontend" }
cranelisp-typecheck = { path = "crates/cranelisp-typecheck" }
cranelisp-backend = { path = "crates/cranelisp-backend" }
cranelisp-runtime = { path = "crates/cranelisp-runtime" }
cranelisp-platform = { path = "crates/cranelisp-platform" }

[dependencies.libc]
version = "0.2"

[dependencies.libloading]
version = "0.8"

[dependencies.notify]
version = "7"

[dev-dependencies]
serial_test = "3"
tempfile = "3"
